#
# List of eBay sites (marketplaces) with all site-specific settings
#
---
- :code: EBAY-US
  :country: US
  :host: www.ebay.com
  :ids: [0, 215]
- :code: EBAY-CA
  :country: CA
  :host: www.ebay.ca
  :ids: [2, 210]
- :code: EBAY-GB
  :country: GB
  :host: www.ebay.co.uk
  :ids: [3]
- :code: EBAY-AU
  :country: AU
  :host: www.ebay.com.au
  :ids:  [15]
- :code: EBAY-AT
  :country: AT
  :host: www.ebay.at
  :ids: [16]
- :code: EBAY-BE
  :country: BE
  :ids: [23, 123]
  :host: www.ebay.be
- :code: EBAY-FR
  :country: FR
  :ids: [71]
  :host: www.ebay.fr
- :code: EBAY-DE
  :country: DE
  :host: www.ebay.de
  :ids: [77]
- :code: EBAY-US.MOTORS
  :country: US
  :host: www.ebay.com/motors
  :ids: [100]
- :code: EBAY-IT
  :country: IT
  :host: www.ebay.it
  :ids: [101]
- :code: EBAY-NL
  :country: NL
  :host: www.ebay.nl
  :ids: [146]
- :code: EBAY-ES
  :country: ES
  :host: www.ebay.es
  :ids: [186]
- :code: EBAY-CH
  :country: CH
  :host: www.ebay.ch
  :ids: [193]
- :code: EBAY-HK
  :country: HK
  :host: www.ebay.com.hk
  :ids: [201]
- :code: EBAY-IN
  :country: IN
  :host: www.ebay.in
  :ids: [203]
- :code: EBAY-IE
  :country: IE
  :host: www.ebay.ie
  :ids: [205]
- :code: EBAY-MY
  :country: MY
  :host: www.ebay.com.my
  :ids: [207]
- :code: EBAY-PH
  :country: PH
  :host: www.ebay.ph
  :ids: [211]
- :code: EBAY-PL
  :country: PL
  :host: www.ebay.pl
  :ids: [212]
- :code: EBAY-SG
  :country: SG
  :host: www.ebay.com.sg
  :ids: [216]
- :code: EBAY-CN
  :country: CN
  :host: ebay.cn
  :ids: [223]
