#
# The list of supported versions of API with version-specific settings.
#
# When API team releases new version of some API, you should
# register the version number with all the necessary settings
# to specify differencies between versions.
#
# Don't forget to reflect new settings in [EbayAPI::Version] model
# (defined at lib/ebay_api/version.rb).
#
# Notice, that [EbayAPI::Version] applies settings from previous version
# to the next version(s) authomatically; here you must define differencies only.
#
---
buy:
  browse:
    - "1_beta.7.0"
  feed:
    - "1_beta.0.0"
  marketing:
    - "1_beta.0.0"
  order:
    - "1_beta.7.0"
commerce:
  taxonomy:
    - "1_beta.0.0"
sell:
  account:
    - "1.1.0"
  analytics:
    - "1.0.0"
  fullfillemt:
    - "1.2.0"
  inventory:
    - "1.1.0"
  marketing:
    - "1.3.0"
  metadata:
    - "1.1.0"
